### ISSUE TITLE
v0.1.0 TODO

### ISSUE THREAD

**Issue by MellKam** [MellKam/soundify#1]
## Authorization flows

- [x] Authorization Code Flow - `AuthCode` namespace
- [x] Implicit Grant Flow - `ImplicitGrant` namespace
- [x] Client Credentials Flow - `ClientCredentials` namespace
- [x] Authorization code with PKCE - `PKCEAuthCode` namespace

## API coverage
- [x] Albums
- - [x] [`GET` /albums/{album_id}](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-an-album) - `getAlbum()`
- - [x] [`GET` /albums](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-multiple-albums) - `getAlbums()`
- - [x] [`GET` /albums/{album_id}/tracks](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-an-albums-tracks) - `getAlbumTracks()`
- - [x] [`GET` /me/albums](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-users-saved-albums) - `getSavedAlbums()`
- - [x] [`PUT` /me/albums](https://developer.spotify.com/documentation/web-api/reference/#/operations/save-albums-user) - `saveAlbums()`, `saveAlbum()`
- - [x] [`DELETE` /me/albums](https://developer.spotify.com/documentation/web-api/reference/#/operations/remove-albums-user) - `removeSavedAlbums()`, `removeSavedAlbum()`
- - [x] [`GET` /me/albums/contains](https://developer.spotify.com/documentation/web-api/reference/#/operations/check-users-saved-albums) - `checkSavedAlbums()`, `checkSavedAlbum()`
- - [x] [`GET` /browse/new-releases](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-new-releases) - `getNewAlbumReleases()`
- [x] Artists
- - [x] [`GET` /artists/{artist_id}](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-an-artist) - `getArtist()`
- - [x] [`GET` /artists](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-multiple-artists) - `getArtists()` 
- - [x] [`GET` /artists/{artist_id}/albums](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-an-artists-albums) - `getArtistAlbums()`
- - [x] [`GET` /artists/{artist_id}/top-tracks](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-an-artists-top-tracks) - `getArtistTopTracks()`
- - [x] [`GET` /artists/{artist_id}/related-artists](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-an-artists-related-artists) - `getArtistRelatedArtists()`
- [x] Tracks
- - [x] [`GET` /tracks/{track_id}](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-track) - `getTrack()` 
- - [x] [`GET` /tracks](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-several-tracks) - `getTracks()`
- - [x] [`GET` /me/tracks](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-users-saved-tracks) - `getSavedTracks()`
- - [x] [`PUT` /me/tracks](https://developer.spotify.com/documentation/web-api/reference/#/operations/save-tracks-user) - `saveTracks()`, `saveTrack()`
- - [x] [`DELETE` /me/tracks](https://developer.spotify.com/documentation/web-api/reference/#/operations/remove-tracks-user) - `removeSavedTracks()`, `removeSavedTrack()`
- - [x] [`GET` /me/tracks/contains](https://developer.spotify.com/documentation/web-api/reference/#/operations/check-users-saved-tracks) - `checkSavedTracks()`, `checkSavedTrack()`
- - [x] [`GET` /audio-features](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-several-audio-features) - `getTracksAudioFeatures()`
- - [x] [`GET` /audio-features/{track_id}](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-audio-features) - `getTrackAudioFeatures()`
- - [x] [`GET` /audio-analysis/{track_id}](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-audio-analysis) - `getTracksAudioAnalysis()`
- - [x] [`GET` /recommendations](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-recommendations) - `getRecommendations()`
- [x] Search
- - [x] [`GET` /search](https://developer.spotify.com/documentation/web-api/reference/#/operations/search) 
- [x] Users
- - [x] [`GET` /me](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-current-users-profile) - `getCurrentUserProfile()`
- - [x] [`GET` /me/top/{type}](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-users-top-artists-and-tracks) - `getUserTopItems()`, `getUserTopArtists()`, `getUserTopTracks()`.
- - [x] [`GET` /users/{user_id}](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-users-profile) - `getUserProfile()`
- - [x] [`PUT` /playlists/{playlist_id}/followers](https://developer.spotify.com/documentation/web-api/reference/#/operations/follow-playlist) - `followPlaylist()`
- - [x] [`DELETE` /playlists/{playlist_id}/followers](https://developer.spotify.com/documentation/web-api/reference/#/operations/unfollow-playlist) - `unfollowPlaylist()`
- - [x] [`GET` /me/following](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-followed) - `getFollowedArtists()`
- - [x] [`PUT` /me/following](https://developer.spotify.com/documentation/web-api/reference/#/operations/follow-artists-users) - `followArtists()`, `followArtist()`, `followUsers()`, `followUser()`
- - [x] [`DELETE` /me/following](https://developer.spotify.com/documentation/web-api/reference/#/operations/unfollow-artists-users) - `unfollowArtists()`, `unfollowArtist()`, `unfollowUsers()`, `unfollowUser()`
- - [x] [`GET` /me/following/contains](https://developer.spotify.com/documentation/web-api/reference/#/operations/check-current-user-follows) - `checkIfUserFollowsArtists()`, `checkIfUserFollowsArtist()`, `checkIfUserFollowsUsers()`, `checkIfUserFollowsUser()`
- - [x] [`GET` /playlists/{playlist_id}/followers/contains](https://developer.spotify.com/documentation/web-api/reference/#/operations/check-if-user-follows-playlist) - `checkIfUsersFollowPlaylist()`, `checkIfUserFollowsPlaylist()`
- [x] Playlists
- - [x] [`GET` /playlists/{playlist_id}](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-playlist)
- - [x] [`PUT` /playlists/{playlist_id}](https://developer.spotify.com/documentation/web-api/reference/#/operations/change-playlist-details) 
- - [x] [`GET` /playlists/{playlist_id}/tracks](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-playlists-tracks)
- - [x] [`POST` /playlists/{playlist_id}/tracks](https://developer.spotify.com/documentation/web-api/reference/#/operations/add-tracks-to-playlist)
- - [x] [`PUT` /playlists/{playlist_id}/tracks](https://developer.spotify.com/documentation/web-api/reference/#/operations/reorder-or-replace-playlists-tracks)
- - [x] [`DELETE` /playlists/{playlist_id}/tracks](https://developer.spotify.com/documentation/web-api/reference/#/operations/remove-tracks-playlist)
- - [x] [`GET` /me/playlists](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-a-list-of-current-users-playlists)
- - [x] [`GET` /users/{user_id}/playlists](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-list-users-playlists)
- - [x] [`POST` /users/{user_id}/playlists](https://developer.spotify.com/documentation/web-api/reference/#/operations/create-playlist)
- - [x] [`GET` /browse/featured-playlists](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-featured-playlists)
- - [x] [`GET` /browse/categories/{category_id}/playlists](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-a-categories-playlists)
- - [x] [`GET` /playlists/{playlist_id}/images](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-playlist-cover)
- - [x] [`PUT` /playlists/{playlist_id}/images](https://developer.spotify.com/documentation/web-api/reference/#/operations/upload-custom-playlist-cover)
- [x] Categories
- - [x] [`GET` /browse/categories](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-categories) - `getBrowseCategories()`
- - [x] [`GET` /browse/categories/{category_id}](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-a-category) - `getBrowseCategory()`
- [x] Genres
- - [x] [`GET` /recommendations/available-genre-seeds](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-recommendation-genres) - `getAvailableGenres()`
- [x] Markets
- - [x] [`GET` /markets](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-available-markets) - `getAvaibleMarkets()`

## Examples

- [x] Examples for web (ImplicitGrant, PKCEAuthCode flows) - [examples/react-implicit-grant](https://github.com/MellKam/soundify/tree/main/examples/react-implicit-grant), [examples/react-pkce-auth](https://github.com/MellKam/soundify/tree/main/examples/react-pkce-auth)
- [x] Example with NEXT.JS and server-side rendering (AuthCode flow) - [examples/next-ssr](https://github.com/MellKam/soundify/tree/main/examples/next-ssr)
- [x] Example with ClientCredentials flow - [deno-client-credentials](https://github.com/MellKam/soundify/tree/main/examples/deno-client-credentials)

## Other
- [x] Ability to retry when 5xx or 429 is received. Example below
```ts
const client = new SpotifyClient("ACCESS_TOKEN", {
  retry5xx: {
    times: 5,
    delay: 0,
  },
  retry429: {
    times: 3,
    delay: 300,
  }
})
```

# Future TODO

- Make tests with json schema validation to ensure that types are correct. Maybe it futures releases. 
- Shows, Episodes, Audiobooks, Chapters, Player endpoints

**Comment by MellKam** [comment]
#Users

- [x] [`GET` /me](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-current-users-profile) - `getCurrentUserProfile()`
- [x] [`GET` /me/top/{type}](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-users-top-artists-and-tracks) - `getUserTopItems()`, `getUserTopArtists()`, `getUserTopTracks()`.
- [ ] [`GET` /users/{user_id}](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-users-profile) - `getUserProfile()`
